version: '3.6'
services:
  postgres:
    image: postgres:11.5-alpine
    logging:
      options:
          max-size: "10m"
          max-file: "3"
    ports:
      - 5432:5432
    volumes:
      - ./:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    restart: always
      